/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gmail.lrchfox3.login.swing;

/**
 *
 * @author lchinchilla
 */
public class NuevoUsuario extends javax.swing.JDialog {

    /**
     * Creates new form NuevoUsuario
     */
    public NuevoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConTitulo1 = new com.gmail.lrchfox3.controles.paneles.JPanelConTitulo();
        jEtiquetaBase1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jTextoBase1 = new com.gmail.lrchfox3.controles.textos.JTextoBase();
        jEtiquetaBase2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jTextoContrasenya1 = new com.gmail.lrchfox3.controles.textos.JTextoContrasenya();
        jEtiquetaBase3 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jTextoContrasenya2 = new com.gmail.lrchfox3.controles.textos.JTextoContrasenya();
        jEtiquetaBase4 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jTextoBase2 = new com.gmail.lrchfox3.controles.textos.JTextoBase();
        jEtiquetaBase5 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jBotonAceptar2 = new com.gmail.lrchfox3.controles.botones.JBotonAceptar();
        jBotonCancelar2 = new com.gmail.lrchfox3.controles.botones.JBotonCancelar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/gmail/lrchfox3/login/resources/application"); // NOI18N
        jPanelConTitulo1.setTitulo(bundle.getString("NUEVO_USUARIO")); // NOI18N

        jEtiquetaBase1.setText(bundle.getString("USER_NAME")); // NOI18N

        jTextoBase1.setRoundedCornerBorder(true);

        jEtiquetaBase2.setText(bundle.getString("PASSWORD")); // NOI18N

        jTextoContrasenya1.setRoundedCornerBorder(true);

        jEtiquetaBase3.setText(bundle.getString("REPETIR_CONTRASENYA")); // NOI18N

        jTextoContrasenya2.setRoundedCornerBorder(true);

        jEtiquetaBase4.setText(bundle.getString("EMAIL")); // NOI18N

        jTextoBase2.setRoundedCornerBorder(true);

        jEtiquetaBase5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jEtiquetaBase5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEtiquetaBase5.setText("imagen");

        jBotonAceptar2.setFlatButton(true);

        jBotonCancelar2.setFlatButton(true);

        javax.swing.GroupLayout jPanelConTitulo1Layout = new javax.swing.GroupLayout(jPanelConTitulo1);
        jPanelConTitulo1.setLayout(jPanelConTitulo1Layout);
        jPanelConTitulo1Layout.setHorizontalGroup(
            jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEtiquetaBase5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelConTitulo1Layout.createSequentialGroup()
                        .addComponent(jEtiquetaBase4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextoBase2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jPanelConTitulo1Layout.createSequentialGroup()
                        .addComponent(jEtiquetaBase3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextoContrasenya2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConTitulo1Layout.createSequentialGroup()
                        .addGroup(jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEtiquetaBase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEtiquetaBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextoBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextoContrasenya1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConTitulo1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jBotonCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonAceptar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanelConTitulo1Layout.setVerticalGroup(
            jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEtiquetaBase5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConTitulo1Layout.createSequentialGroup()
                        .addGroup(jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextoBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEtiquetaBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEtiquetaBase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextoContrasenya1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEtiquetaBase3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextoContrasenya2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEtiquetaBase4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextoBase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonAceptar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelConTitulo1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoUsuario dialog = new NuevoUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gmail.lrchfox3.controles.botones.JBotonAceptar jBotonAceptar2;
    private com.gmail.lrchfox3.controles.botones.JBotonCancelar jBotonCancelar2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase jEtiquetaBase1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase jEtiquetaBase2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase jEtiquetaBase3;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase jEtiquetaBase4;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase jEtiquetaBase5;
    private com.gmail.lrchfox3.controles.paneles.JPanelConTitulo jPanelConTitulo1;
    private com.gmail.lrchfox3.controles.textos.JTextoBase jTextoBase1;
    private com.gmail.lrchfox3.controles.textos.JTextoBase jTextoBase2;
    private com.gmail.lrchfox3.controles.textos.JTextoContrasenya jTextoContrasenya1;
    private com.gmail.lrchfox3.controles.textos.JTextoContrasenya jTextoContrasenya2;
    // End of variables declaration//GEN-END:variables
}
